### ISSUE TITLE
Odd looking shadow in Glyphs 3.2

### ISSUE THREAD

**Issue by Mark2Mark** [mekkablue/System7Shadow#1]
<img width="933" alt="KakaoTalk_Image_2023-03-07-15-26-02" src="https://user-images.githubusercontent.com/5824595/223450992-a573bec3-68d5-44d4-9f54-6576b10a5920.png">

It seems, that the Depth X and Depth Y are not concatenated, but instead draw separate shadows now on top of the actually desired shadow X+Y

**Comment by Mark2Mark** [comment]
Happens in 3180 and in 3151

plugin did not work in 3179 (#2)

**Comment by mekkablue** [comment]
This is intended behavior for the System 7 shadow.

**Comment by Mark2Mark** [comment]
I would expect the outside bits N/E/S/W to be straight lines though.
